//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STCrawler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class STConfigurations : global::System.Configuration.ApplicationSettingsBase {
        
        private static STConfigurations defaultInstance = ((STConfigurations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new STConfigurations())));
        
        public static STConfigurations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public string ReAttempts {
            get {
                return ((string)(this["ReAttempts"]));
            }
            set {
                this["ReAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2,4,6,8,9")]
        public string ScheduledHour {
            get {
                return ((string)(this["ScheduledHour"]));
            }
            set {
                this["ScheduledHour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("61053682~smile@15")]
        public string ST_UsernamePassword {
            get {
                return ((string)(this["ST_UsernamePassword"]));
            }
            set {
                this["ST_UsernamePassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3F9IjsjyFoBWrcI77yBOONuSBI/Yqg4cN6TMedM9JynWc1CsFu5vhYdLN5u9jfBAZy3HjtW6cmCwJisFF" +
            "EWzKGtASvW8UOSszrCImLKvopgauwgCzpNec5AEgVpRFvwf5XztrX6AukVrAy8zaiR8PLgZzHe7K9mqe" +
            "3tP/G9ltJ8=")]
        public string Code {
            get {
                return ((string)(this["Code"]));
            }
            set {
                this["Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.socialtrade.biz/User/MyePoints.aspx")]
        public string ST_URL {
            get {
                return ((string)(this["ST_URL"]));
            }
            set {
                this["ST_URL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sid")]
        public string theme {
            get {
                return ((string)(this["theme"]));
            }
            set {
                this["theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//*[@id=\'ajax-content\']/table[2]/tbody/tr[{0}]/td[4]/span")]
        public string placeholder {
            get {
                return ((string)(this["placeholder"]));
            }
            set {
                this["placeholder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public string ClosePopupsAfter {
            get {
                return ((string)(this["ClosePopupsAfter"]));
            }
            set {
                this["ClosePopupsAfter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("35")]
        public string PopupWaitTiming {
            get {
                return ((string)(this["PopupWaitTiming"]));
            }
            set {
                this["PopupWaitTiming"] = value;
            }
        }
    }
}
