//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STCrawler {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class STConfigurations : global::System.Configuration.ApplicationSettingsBase {
        
        private static STConfigurations defaultInstance = ((STConfigurations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new STConfigurations())));
        
        public static STConfigurations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Acer\\AppData\\Local\\Google\\Chrome\\Application\\chrome.exe")]
        public string ChromePath {
            get {
                return ((string)(this["ChromePath"]));
            }
        }
    }
}
